import test from 'node:test';
import assert from 'node:assert/strict';
import * as sim from '../src/simulation.js';
function owned(item){const s=sim.createState();s.buttons=999;sim.place(s,item,'kitchen',0);return s}
const progression=s=>({buttons:s.buttons,earned:s.earnedToday,cares:s.cares,bonds:s.dolls.map(d=>d.bond),mastery:{...s.activities.mastery},wishes:[...s.wishes],milestones:[...s.milestones]});
test('plant watering is once per in-game house day and changes no reward progression',()=>{const s=owned('plant'),id=s.decor[0].id,before=progression(s);assert.equal(sim.useDecor(s,id).effect,'water');assert.equal(s.decor[0].tendedDay,1);const snapshot=structuredClone(s);assert.equal(sim.useDecor(s,id).reason,'alreadyTended');assert.deepEqual(s,snapshot);assert.deepEqual(progression(s),before);s.day=2;assert.equal(sim.useDecor(s,id).ok,true);assert.equal(s.decor[0].tendedDay,2)});
test('lamp toggles persistently with no reward and follows an atomic move',()=>{const s=owned('lamp'),id=s.decor[0].id,before=progression(s);assert.equal(sim.useDecor(s,id).active,true);sim.moveDecor(s,id,'bedroom',2);assert.equal(s.decor[0].active,true);assert.equal(sim.useDecor(s,id).active,false);assert.deepEqual(progression(s),before)});
test('music box and mobile record bounded animation timestamps without rewards',()=>{for(const item of ['musicbox','mobile']){const s=owned(item),id=s.decor[0].id,before=progression(s);s.elapsed=42;const r=sim.useDecor(s,id);assert.equal(r.effect,item==='musicbox'?'wind':'rock');assert.equal(s.decor[0].lastUse,42);assert.equal(s.decor[0].tendedDay,1);assert.deepEqual(progression(s),before)}});
test('bear, rug and unknown IDs cannot change state through keepsake use',()=>{for(const item of ['bear','rug']){const s=owned(item),before=structuredClone(s);assert.equal(sim.useDecor(s,s.decor[0].id).reason,'notInteractive');assert.deepEqual(s,before)}const s=sim.createState(),before=structuredClone(s);assert.equal(sim.useDecor(s,999).reason,'invalid');assert.deepEqual(s,before)});
test('version-one restore defaults and clamps reactive fields',()=>{const old=owned('lamp');delete old.decor[0].active;delete old.decor[0].tendedDay;delete old.decor[0].lastUse;let r=sim.restore(JSON.stringify(old));assert.deepEqual({active:r.decor[0].active,tendedDay:r.decor[0].tendedDay,lastUse:r.decor[0].lastUse},{active:false,tendedDay:0,lastUse:-10});old.day=3;old.elapsed=50;Object.assign(old.decor[0],{active:'yes',tendedDay:99,lastUse:999});r=sim.restore(JSON.stringify(old));assert.deepEqual({active:r.decor[0].active,tendedDay:r.decor[0].tendedDay,lastUse:r.decor[0].lastUse},{active:false,tendedDay:3,lastUse:50})});
