import * as T from 'three';
import {paintedTexture,craftMaterial} from './textiles.js';
const materials=new Map(), geometries=new Map();
export const palette={cream:0xeedac1,wood:0x96715e,dark:0x655061,gold:0xc59b60,rose:0xce91a4,mint:0x8fb9aa,lavender:0xb3a0c8,ink:0x352b3d};
export function mat(color,extra={}){if(color===palette.wood&&!Object.keys(extra).length)return craftMaterial(color,'wood');if(color===palette.gold)extra={metalness:.48,roughness:.3,...extra};const key=JSON.stringify([color,extra]);if(!materials.has(key))materials.set(key,new T.MeshStandardMaterial({color,roughness:.82,...extra}));return materials.get(key)}
function geometry(key,create){if(!geometries.has(key))geometries.set(key,create());return geometries.get(key)}
function mesh(parent,g,m,x,y,z,sx=1,sy=1,sz=1){const o=new T.Mesh(g,typeof m==='number'?mat(m):m);o.position.set(x,y,z);o.scale.set(sx,sy,sz);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
export function box(p,x,y,z,w,h,d,c,rounded=false){const g=geometry(rounded?'round':'box',()=>{const g=new T.BoxGeometry(1,1,1,rounded?4:1,rounded?4:1,rounded?4:1);if(rounded){const a=g.attributes.position,v=new T.Vector3(),inner=new T.Vector3();for(let i=0;i<a.count;i++){v.fromBufferAttribute(a,i);inner.copy(v).clampScalar(-.40,.40);v.sub(inner).normalize().multiplyScalar(.10).add(inner);a.setXYZ(i,v.x,v.y,v.z)}g.computeVertexNormals()}return g});return mesh(p,g,c,x,y,z,w,h,d)}
export function ball(p,x,y,z,rx,ry,rz,c){return mesh(p,geometry('sphere',()=>new T.SphereGeometry(1,16,12)),c,x,y,z,rx,ry,rz)}
export function cylinder(p,x,y,z,r,h,c,bottom=1){return mesh(p,geometry(`cyl:${bottom}`,()=>new T.CylinderGeometry(1,bottom,1,20)),c,x,y,z,r,h,r)}
export function ring(p,x,y,z,r,t,c,flat=false){const o=mesh(p,geometry(`torus:${t/r}`,()=>new T.TorusGeometry(1,t/r,6,32)),c,x,y,z,r,r,r);if(flat)o.rotation.x=-Math.PI/2;return o}
export function line(p,a,b,r,c){const aa=new T.Vector3(...a),bb=new T.Vector3(...b),mid=aa.clone().add(bb).multiplyScalar(.5);const o=cylinder(p,...mid.toArray(),r,aa.distanceTo(bb),c);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),bb.sub(aa).normalize());return o}
export function arch(p,x,y,z,w,h,c,depth=.06){const r=w/2,s=new T.Shape();s.moveTo(-r,0);s.lineTo(r,0);s.lineTo(r,h-r);s.absarc(0,h-r,r,0,Math.PI,false);s.lineTo(-r,0);const g=new T.ExtrudeGeometry(s,{depth,bevelEnabled:false,curveSegments:20});return mesh(p,g,c,x,y,z)}
export function texture(kind,colors){return paintedTexture(kind,colors)}
export function texturedPlane(p,x,y,z,w,h,tex,flat=false){const o=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshStandardMaterial({map:tex,roughness:1,side:T.DoubleSide}));o.position.set(x,y,z);if(flat)o.rotation.x=-Math.PI/2;o.receiveShadow=true;p.add(o);return o}
export function plant(p,x,y,z,scale=1){const g=new T.Group();g.position.set(x,y,z);g.scale.setScalar(scale);p.add(g);cylinder(g,0,.17,0,.19,.34,0xba827b,.72);ring(g,0,.34,0,.19,.025,palette.cream,true);cylinder(g,0,.34,0,.155,.015,0x68534d);for(let i=0;i<7;i++){const a=i*2.4;const end=[Math.cos(a)*.22,.65+(i%3)*.13,Math.sin(a)*.22];line(g,[0,.32,0],end,.014,0x718b62);const leaf=ball(g,...end,.13,.065,.22,i%2?0x91ad82:0x698b72);leaf.rotation.set(.45,a,.45)}return g}
export function lamp(p,x,y,z,scale=1){const g=new T.Group();g.position.set(x,y,z);g.scale.setScalar(scale);p.add(g);cylinder(g,0,.035,0,.25,.07,palette.gold);cylinder(g,0,.47,0,.027,.9,palette.gold);const shade=cylinder(g,0,.98,0,.22,.38,0xefcda1,1.65);ring(g,0,.79,0,.36,.022,palette.gold,true);ball(g,0,1.2,0,.04,.06,.04,palette.gold);return {group:g,shade}}
export function cup(p,x,y,z,color=palette.cream){cylinder(p,x,y+.065,z,.075,.13,color,.8);cylinder(p,x,y+.132,z,.061,.004,0x775040);ring(p,x+.078,y+.07,z,.05,.012,color);cylinder(p,x,y+.009,z,.11,.012,color)}
export function books(p,x,y,z){for(let i=0;i<5;i++){const b=box(p,x+i*.11,y+.18+(i%2)*.03,z,.08,.36+(i%2)*.06,.24,[0xb7858a,0x829c99,0xd9bd8b,0xa198b4,0x709687][i]);b.rotation.z=(i===4?-.12:0);box(p,x+i*.11,y+.29,z+.124,.055,.013,.01,palette.gold)}}
// Static geometry is grouped into instances by geometry/material: detail without a draw call per teacup.
export function batch(root){root.updateMatrixWorld(true);const groups=new Map();root.traverse(o=>{if(o.isMesh&&!Array.isArray(o.material)&&!o.userData.noBatch){const key=o.geometry.uuid+o.material.uuid;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(o)}});const inverse=root.matrixWorld.clone().invert();for(const list of groups.values()){if(list.length<3)continue;const inst=new T.InstancedMesh(list[0].geometry,list[0].material,list.length);for(let i=0;i<list.length;i++)inst.setMatrixAt(i,inverse.clone().multiply(list[i].matrixWorld));inst.castShadow=true;inst.receiveShadow=true;for(const o of list)o.removeFromParent();root.add(inst)}return root}
export function disposeTree(root,{shared=false}={}){const gs=new Set(),ms=new Set();root.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material])ms.add(m)}});if(!shared){for(const g of gs)g.dispose();for(const m of ms){if(m.map)m.map.dispose();m.dispose()}}root.removeFromParent()}
