"""Exercise earned rituals and room changes against the real built app."""
import json, os, subprocess, time, urllib.request
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'artifacts'/'expansion'; OUT.mkdir(parents=True,exist_ok=True)
BASE=os.environ.get('PLAY_URL','http://127.0.0.1:4188')
env={**os.environ,'PORT':'4188'}
server=None if os.environ.get('PLAY_URL') else subprocess.Popen(['node','scripts/serve.mjs','dist'],cwd=ROOT,env=env,stdout=(OUT/'server.log').open('w'),stderr=subprocess.STDOUT)
checks=[]
def check(name,ok):
 checks.append({'name':name,'passed':bool(ok)})
 assert ok,name
try:
 for _ in range(80):
  try:urllib.request.urlopen(BASE,timeout=1);break
  except Exception:time.sleep(.1)
 with sync_playwright() as p:
  opts={'headless':True,'args':['--use-angle=swiftshader','--enable-unsafe-swiftshader','--enable-webgl']}
  if os.environ.get('CHROMIUM_PATH'):opts['executable_path']=os.environ['CHROMIUM_PATH']
  browser=p.chromium.launch(**opts)
  page=browser.new_page(viewport={'width':1280,'height':900})
  page.add_init_script("const seeded=sessionStorage.getItem('expansion-fixture');if(seeded){localStorage.setItem('bait-al-dumiah.v1',seeded);sessionStorage.removeItem('expansion-fixture')}")
  errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
  page.goto(BASE+'/?debug=1');page.wait_for_function('window.dollhouse && !document.querySelector("#loading")')
  check('WebGL scene starts',page.locator('.error-screen').count()==0)
  state=lambda:page.evaluate('window.dollhouse.state()')
  point=next(o for o in page.evaluate('window.dollhouse.objects()') if o['key']=='prop:tea-set')
  page.mouse.click(point['x'],point['y'])
  check('whole-house object pick focuses its room before the paused sheet',page.locator('.object-detail').count()==1 and page.evaluate('window.dollhouse.visual().focusedRoom==="kitchen" && !window.dollhouse.visual().cameraMoving'))
  page.locator('[data-action="close"]').click()
  page.locator('[data-room="kitchen"]').click();page.wait_for_function('!window.dollhouse.visual().cameraMoving')
  point=next(o for o in page.evaluate('window.dollhouse.objects()') if o['key']=='prop:tea-set')
  page.mouse.click(point['x'],point['y'])
  check('actual tea-set ray pick opens its contextual actions',page.locator('.object-detail [data-action="begin-activity"][data-id="tea"]').count()==1)
  page.screenshot(path=str(OUT/'08-object-selection.png'))
  page.locator('[data-action="close"]').click()
  page.locator('[data-action="panel-activities"]').click()
  check('activity selection has three rituals',page.locator('.ritual-card').count()==3)
  page.screenshot(path=str(OUT/'01-rituals.png'))
  page.locator('[data-action="begin-activity"][data-id="tea"]').click()
  pattern=state()['activities']['active']['pattern'];before=state()['buttons']
  page.locator(f'[data-choice="{(pattern[0]+1)%4}"]').click()
  check('mistake keeps cursor and buttons safe',state()['activities']['active']['cursor']==0 and state()['buttons']==before)
  page.screenshot(path=str(OUT/'02-tea-play.png'))
  for choice in pattern:page.locator(f'[data-choice="{choice}"]').click()
  check('completed ritual rewards earned mastery',state()['activities']['mastery']['tea']==1 and state()['buttons']==before+7)
  check('result is visible',page.locator('.ritual-result').is_visible())
  page.screenshot(path=str(OUT/'03-earned-reward.png'))
  page.locator('[data-action="close"]').click()
  page.wait_for_function('document.querySelector(".object-controls") && !document.querySelector(".object-controls").hidden')
  check('ritual camera and accessible objects agree after completion',page.locator('[data-object="prop:tea-set"]').is_visible() and page.locator('[data-room="kitchen"]').get_attribute('aria-pressed')=='true')
  page.reload();page.wait_for_function('window.dollhouse && !document.querySelector("#loading")')
  check('mastery survives reload',state()['activities']['mastery']['tea']==1)
  # Seed an earned-state fixture to inspect restoration and all-tier rendering.
  page.evaluate('''() => {const s=window.dollhouse.state();s.buttons=1000;s.activities.mastery={tea:6,stitch:6,lullaby:6};sessionStorage.setItem('expansion-fixture',JSON.stringify(s));}''')
  page.reload();page.wait_for_function('window.dollhouse && !document.querySelector("#loading")')
  page.locator('[data-action="panel-activities"]').click()
  page.locator('[data-action="restore-room"][data-id="kitchen"]').click()
  check('restoration spends displayed cost and persists tier',state()['buttons']==955 and state()['restoration']['kitchen']==1)
  page.wait_for_function('!window.dollhouse.visual().cameraMoving')
  page.screenshot(path=str(OUT/'04-restored-kitchen.png'))
  page.evaluate('''() => {const s=window.dollhouse.state();s.restoration={kitchen:3,parlor:3,studio:3,bedroom:3};sessionStorage.setItem('expansion-fixture',JSON.stringify(s));}''')
  page.reload();page.wait_for_function('window.dollhouse && !document.querySelector("#loading")')
  page.screenshot(path=str(OUT/'05-restored-house.png'))
  stats=page.evaluate('window.dollhouse.stats()')
  (OUT/'render-stats.json').write_text(json.dumps(stats,indent=2))
  check('restored house stays within 400k triangles',stats['triangles']<400000)
  page.locator('[data-action="light"]').click();page.wait_for_timeout(900)
  page.screenshot(path=str(OUT/'06-restored-night.png'))
  page.set_viewport_size({'width':390,'height':844})
  page.locator('[data-action="panel-settings"]').click();page.locator('[data-field="locale"]').select_option('ar')
  page.locator('[data-action="close"]').click();page.locator('[data-action="panel-activities"]').click()
  check('Arabic direction and ritual titles',page.locator('html').get_attribute('dir')=='rtl' and 'شاي' in page.locator('.ritual-catalog').inner_text())
  page.locator('[data-action="begin-activity"][data-id="stitch"]').click()
  page.screenshot(path=str(OUT/'07-mobile-arabic.png'))
  check('embroidery starts in explicit study mode',state()['activities']['active']['phase']=='study' and page.locator('.ritual-choice:disabled').count()==4)
  pattern=state()['activities']['active']['pattern']
  page.locator('[data-action="recall-ready"]').click()
  check('recall hides thread choices until a free hint',page.locator('.pattern-step').first.locator('span').inner_text()=='تذكّر')
  page.locator('[data-action="activity-hint"]').click()
  check('hint reveals the pattern without spending buttons',state()['activities']['active']['hint'])
  for choice in pattern:page.locator(f'[data-choice="{choice}"]').click()
  check('recall completes through real choice buttons',state()['activities']['mastery']['stitch']==7)
  check('mobile choices all have 44px targets',page.locator('.ritual-choice').evaluate_all('(els)=>els.every(e=>{const r=e.getBoundingClientRect();return r.width>=44 && r.height>=44})'))
  check('no horizontal page overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
  page.locator('[data-action="end-activity"]').click();page.locator('[data-action="panel-settings"]').click();page.locator('[data-field="motion"]').check()
  check('reduced motion setting applies',state()['settings']['reducedMotion'])
  page.locator('[data-action="close"]').click()
  page.set_viewport_size({'width':1280,'height':900})
  page.locator('[data-action="panel-decorate"]').click();page.locator('[data-action="choose-item"][data-id="bear"]').click();page.locator('[data-action="place-confirm"]').click()
  decor=state()['decor'][-1];key='decor:'+str(decor['id']);buttons=state()['buttons']
  page.locator('[data-room="kitchen"]').click();page.wait_for_function('!window.dollhouse.visual().cameraMoving')
  point=next(o for o in page.evaluate('window.dollhouse.objects()') if o['key']==key)
  page.mouse.move(point['x'],point['y']);page.mouse.down();page.mouse.move(point['x']+50,point['y']);page.mouse.move(point['x'],point['y']);page.mouse.up()
  check('a camera drag cannot select a decoration',page.locator('.object-detail').count()==0)
  # Recenter after the drag before selecting the physical object.
  page.locator('[data-room="kitchen"]').click();page.wait_for_function('!window.dollhouse.visual().cameraMoving')
  point=next(o for o in page.evaluate('window.dollhouse.objects()') if o['key']==key);page.mouse.click(point['x'],point['y'])
  check('owned decoration is selectable in the scene',page.locator('[data-action="rotate-object"]').count()==1)
  page.screenshot(path=str(OUT/'09-keepsake-actions-arabic.png'))
  page.locator('[data-action="rotate-object"]').click();check('quarter turn changes the selected owned object',state()['decor'][-1]['rotation']==1)
  page.locator('[data-action="move-object"]').click();page.locator('#place-room').select_option('studio');page.locator('#place-slot').select_option('2');page.locator('[data-action="place-confirm"]').click()
  check('move preserves ownership, orientation and currency',state()['decor'][-1]['id']==decor['id'] and state()['decor'][-1]['room']=='studio' and state()['decor'][-1]['slot']==2 and state()['decor'][-1]['rotation']==1 and state()['buttons']==buttons)
  page.wait_for_function('!window.dollhouse.visual().cameraMoving');page.screenshot(path=str(OUT/'10-moved-keepsake.png'))
  page.reload();page.wait_for_function('window.dollhouse && !document.querySelector("#loading")')
  check('manipulated object survives reload',state()['decor'][-1]['room']=='studio' and state()['decor'][-1]['rotation']==1)
  page.locator('[data-room="bedroom"]').click();page.wait_for_function('!window.dollhouse.visual().cameraMoving')
  page.locator('[data-object="prop:moon-bed"]').click();page.locator('[data-action="begin-activity"][data-id="lullaby"]').click()
  pattern=state()['activities']['active']['pattern'];page.screenshot(path=str(OUT/'11-reverse-echo.png'))
  for choice in reversed(pattern):page.locator(f'[data-choice="{choice}"]').click()
  check('reverse echo completes through real object ritual',state()['activities']['mastery']['lullaby']==7)
  check('no JavaScript page errors',not errors)
  browser.close()
finally:
 (OUT/'results.json').write_text(json.dumps(checks,indent=2))
 if server:server.terminate()
print(json.dumps({'passed':len(checks),'checks':checks},indent=2))
